<?php
/**
 * Created by PhpStorm.
 * User: tungphung
 * Date: 17/4/17
 * Time: 11:00 AM
 */

namespace api\common\models;


class Node extends \common\models\Node
{
    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }
    public function extraFields()
    {
        return parent::extraFields(); // TODO: Change the autogenerated stub
    }

}